routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

Route::get('register/activate/resend', 'AuthController@resendActivationCode');

Route::get('/2fa', 'Admin\Google2FAController@getValidateToken')->name('2fa');
Route::post('/2fa', 'Admin\Google2FAController@validateSecretKey')->name('2fa.validate');


Route::group(['middleware' => 'guest'], function() {
    Route::get('/register', 'AuthController@registerForm')->name('register');
    Route::post('/register', 'AuthController@register');
    Route::get('/login', 'AuthController@loginForm');
    Route::post('/login', 'AuthController@login')->name('login')->middleware('g2fa');
    Route::get('/register/activate', 'AuthController@activate')->name('activate');
});


Route::group(['middleware' => 'auth'], function() {
    Route::get('/logout', 'AuthController@logout')->name('logout');
});


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function (){
    Route::get('/', 'DashboardController@index')->name('admin.index');
    Route::resource('/info', 'InfoController')->only(['index', 'store']);
    Route::get('/referral', 'ReferralController@index')->name('referral');
    Route::get('/settings', 'SettingController@index')->name('settings.index');
    Route::post('/settings', 'SettingController@store')->name('settings.store');
    Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor')->name('g2fa.enable');
    Route::get('/2fa/disable', 'Google2FAController@disableTwoFactor')->name('g2fa.disable');
});

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
	<h1>Dashboard ico</h1>
@endsection

resources/views/admin/info.blade.php
@extends('admin.layout')

@section('content')
	<h1 style=>Personal information</h1>
	<div class="info-block">
		<div class="info-table">
			<table border="solid">
				<tr>
					<td>Email:</td>
					<td>@if($user->email != null){{$user->email}}@endif</td>
				</tr>
				<tr>
					<td>Name:</td>
					<td>@if($user->name != null){{$user->name}}@endif</td>
				</tr>
				<tr>
					<td>Last Name:</td>
					<td>@if($user->last_name != null){{$user->last_name}}@endif</td>
				</tr>
				<tr>
					<td>Phone:</td>
					<td>@if($user->phone_number != null){{$user->phone_number}}@endif</td>
				</tr>
				<tr>
					<td>BTC address:</td>
					<td>@if($user->btc != null){{$user->btc}}@endif</td>
				</tr>
			</table>
		</div>
		<div class="info-form-block">
			{{Form::open(['route' => 'info.store', 'class' => 'info-form'])}}
			<input type="text" name="name" placeholder="First Name" value="">
			<input type="text" name="last_name" placeholder="Last Name" value="">
			<input type="tel" name="phone_number" placeholder="Phone" value="">
			<input type="text" name="btc" placeholder="BTC address" value="">
			<button type="submit">Save information</button>
			{{Form::close()}}
		</div>
	</div>
@endsection

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ICO</title>
    <style type="text/css">

        .info-block {
            display: flex;
        }

        .info-form {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
        }

        .info-table {
            margin-right: 20px;
        }

        .info-form-block {
            margin-right: 20px;
        }

        .info-form-block input{
            margin-bottom: 10px;
        }

        .g2fa-block {
            display: flex;
        }

        .setting-item {
            display: flex;
            align-items: center;
        }

        .setting-item p{
            margin-right: 15px;
        }
    </style>
</head>
<body>
<nav>
    <ul style="display: flex;">
        <li style="margin-left: 20px;"><a href="{{route('admin.index')}}">Home</a></li>
        <li style="margin-left: 20px;"><a href="{{route('info.index')}}">Info</a></li>
        <li style="margin-left: 20px;"><a href="{{route('referral')}}">Referral System</a></li>
        @if(Auth::user()->google2fa_secret)
            <li style="margin-left: 20px;"><a href="{{route('g2fa.disable')}}">Disable Google2FA</a></li>
        @else
            <li style="margin-left: 20px;"><a href="{{route('g2fa.enable')}}" onclick="return confirm('are you sure?')">Enable Google2FA</a></li>
        @endif
        <li style="margin-left: 20px;"><a href="{{route('settings.index')}}">Settings</a></li>
        <li style="margin-left: 20px;"><a href="{{route('logout')}}">Logout</a></li>
    </ul>
</nav>
    @if(session('status'))
        <div class="container">
            <div class="row">
                <div class="col-md-10">
                    <div class="alert alert-danger">
                        <ul>
                            <li>{!! session('status') !!}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    @endif
    @yield('content')
</body>
</html>

resources/views/admin/referral.blade.php
@extends('admin.layout')

@section('content')
    <h1>Referral page</h1>
    <div>
        <div class="info-ref-link" style="width: 30%;">
            <p style="margin: 0;">Referral link:</p>
            <input style="width: 100%;" type="text" value="{{route('register') .'?ref='. $user->referrals->referral_link}}" readonly>
        </div>
        <div class="info-ref-count" style="display: flex;flex-direction: column;">
            <p style="margin: 30px 0;">Count of referral users:<span> {{$referrals}}</span></p>
            <p style="margin: 0;">Count of sub-referral users:<span> {{$sub_referrals}}</span></p>
        </div>
    </div>
@endsection

resources/views/admin/setting.blade.php
@extends('admin.layout')

@section('content')
    <h1>Admin Settings</h1>
    {{Form::open([
        'route' => 'settings.store',
        'method' => 'post',
    ])}}
    {{$referral_level}}
    <div class="settings-block">
        <div class="setting-item">
            <p>Referral level:</p>
            <select name="referral_level" id="referral_level">
                @for($i = 0; $i < 5; $i++)
                    @if(\App\Settings::getSetting('referral_level') == $i)
                        <option value="{{$i}}" selected>{{$i}}</option>
                    @else
                        <option value="{{$i}}">{{$i}}</option>
                    @endif
                @endfor
            </select>
        </div>
    </div>
    <button type="submit">Save settings</button>
    {{Form::close()}}
@endsection